# Generated by Django 4.2.29 on 2026-03-15 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_contractsignature_and_more"),
        ("accounts", "0002_certificationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("bank", "Banque"),
                            ("insurance", "Assurance"),
                            ("notary", "Notaire"),
                            ("agency", "Agence immobiliere"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/logos/"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% commission",
                        max_digits=5,
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des services proposes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referral_code", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("registered", "Inscrit"),
                            ("converted", "Converti"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(blank=True, default="bonus", max_length=30),
                ),
                (
                    "reward_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("reward_claimed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parrainage",
                "verbose_name_plural": "Parrainages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referral_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="credit_request, insurance_quote, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("contacted", "Contacte"),
                            ("converted", "Converti"),
                            ("rejected", "Rejete"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="accounts.partner",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_referrals",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande partenaire",
                "verbose_name_plural": "Demandes partenaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AmbassadorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ambassador_code", models.CharField(max_length=20, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Argent"),
                            ("gold", "Or"),
                            ("platinum", "Platine"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("total_referrals", models.IntegerField(default=0)),
                ("total_conversions", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="% par transaction",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambassador_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambassadeur",
                "verbose_name_plural": "Ambassadeurs",
            },
        ),
    ]
