# Generated by Django 5.1.15 on 2026-03-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_partner_referralprogram_partnerreferral_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("visiteur", "Visiteur"),
                    ("acheteur", "Acheteur"),
                    ("vendeur", "Vendeur"),
                    ("promoteur", "Promoteur immobilier"),
                    ("geometre", "Géomètre / Validateur"),
                    ("admin", "Administrateur"),
                ],
                default="visiteur",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
    ]
