# Generated by Django 5.1.15 on 2026-02-09 00:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parcelles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="montant (FCFA)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("reserved", "Réservé"),
                            ("paid", "Payé"),
                            ("completed", "Finalisé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="mode de paiement",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "reserved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de réservation"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de finalisation"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'annulation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acheteur",
                    ),
                ),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="parcelles.parcelle",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["buyer", "-created_at"],
                        name="transaction_buyer_i_053873_idx",
                    ),
                    models.Index(
                        fields=["seller", "-created_at"],
                        name="transaction_seller__8cf6c4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="transaction_status_71abbb_idx"
                    ),
                ],
            },
        ),
    ]
