# Generated by Django 4.2.29 on 2026-03-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parcelles", "0002_promotioncampaign_parcellereaction"),
        ("transactions", "0002_escrow_bonvisite_compromis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="prix du bien (FCFA)",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="apport initial (FCFA)",
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="montant emprunt (FCFA)",
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(verbose_name="durée (mois)"),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="taux d'intérêt annuel (%)",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="mensualité (FCFA)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="coût total (FCFA)",
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="total intérêts (FCFA)",
                    ),
                ),
                (
                    "amortization_table",
                    models.JSONField(
                        blank=True, default=list, verbose_name="tableau d'amortissement"
                    ),
                ),
                (
                    "is_feasible",
                    models.BooleanField(default=True, verbose_name="réalisable"),
                ),
                (
                    "feasibility_notes",
                    models.TextField(blank=True, verbose_name="notes de faisabilité"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations",
                        to="parcelles.parcelle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation d'achat",
                "verbose_name_plural": "Simulations d'achat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Créée"),
                            ("reserved", "Réservée"),
                            ("escrow_funded", "Séquestre alimenté"),
                            ("docs_validated", "Documents validés"),
                            ("compromis_generated", "Compromis généré"),
                            ("compromis_signed", "Compromis signé"),
                            ("paid", "Payée"),
                            ("completed", "Finalisée"),
                            ("cancelled", "Annulée"),
                            ("disputed", "Litige ouvert"),
                            ("dispute_resolved", "Litige résolu"),
                            ("refund_initiated", "Remboursement initié"),
                            ("refund_completed", "Remboursement effectué"),
                            ("note_added", "Note ajoutée"),
                        ],
                        max_length=25,
                        verbose_name="type",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ancien statut"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="nouveau statut"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="transactions.transaction",
                        verbose_name="transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement transaction",
                "verbose_name_plural": "Événements transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction", "-created_at"],
                        name="transaction_transac_936676_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="score global (0-100)"
                    ),
                ),
                ("score_kyc", models.FloatField(default=0, verbose_name="score KYC")),
                (
                    "score_revenue",
                    models.FloatField(default=0, verbose_name="score revenus"),
                ),
                (
                    "score_history",
                    models.FloatField(default=0, verbose_name="score historique"),
                ),
                (
                    "score_mobile_money",
                    models.FloatField(default=0, verbose_name="score Mobile Money"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Excellent (80-100)"),
                            ("B", "Bon (60-79)"),
                            ("C", "Moyen (40-59)"),
                            ("D", "Faible (20-39)"),
                            ("E", "Insuffisant (0-19)"),
                        ],
                        max_length=1,
                        verbose_name="grade",
                    ),
                ),
                (
                    "max_purchase_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="capacité max achat (FCFA)",
                    ),
                ),
                (
                    "monthly_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="capacité mensuelle (FCFA)",
                    ),
                ),
                (
                    "revenue_declared",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="revenus déclarés (FCFA/mois)",
                    ),
                ),
                (
                    "revenue_proof",
                    models.FileField(
                        blank=True,
                        upload_to="scoring/revenue/%Y/%m/",
                        verbose_name="justificatif revenus",
                    ),
                ),
                (
                    "mobile_money_verified",
                    models.BooleanField(
                        default=False, verbose_name="compte Mobile Money vérifié"
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="employeur"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("salarie", "Salarié"),
                            ("fonctionnaire", "Fonctionnaire"),
                            ("independant", "Indépendant"),
                            ("entrepreneur", "Entrepreneur"),
                            ("informel", "Secteur informel"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="type d'emploi",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="détails du calcul"
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="dernier calcul"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_score",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score financier",
                "verbose_name_plural": "Scores financiers",
                "indexes": [
                    models.Index(
                        fields=["user"], name="transaction_user_id_13cb33_idx"
                    ),
                    models.Index(fields=["grade"], name="transaction_grade_c4755f_idx"),
                ],
            },
        ),
    ]
