# Generated by Django 4.2.29 on 2026-03-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0003_simulationresult_transactionevent_financialscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Créée"),
                    ("reserved", "Réservée"),
                    ("escrow_funded", "Séquestre alimenté"),
                    ("docs_validated", "Documents validés"),
                    ("compromis_generated", "Compromis généré"),
                    ("compromis_signed", "Compromis signé"),
                    ("paid", "Payée"),
                    ("completed", "Finalisée"),
                    ("cancelled", "Annulée"),
                    ("disputed", "Litige ouvert"),
                    ("dispute_resolved", "Litige résolu"),
                    ("refund_initiated", "Remboursement initié"),
                    ("refund_completed", "Remboursement effectué"),
                    ("note_added", "Note ajoutée"),
                    ("approval_requested", "Approbation demandée"),
                    ("approval_approved", "Approbation accordée"),
                    ("approval_rejected", "Approbation refusée"),
                ],
                max_length=25,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="TransactionApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("reserve", "Réservation"),
                            ("escrow_fund", "Alimentation séquestre"),
                            ("docs_confirm", "Confirmation documents"),
                            ("compromis", "Compromis de vente"),
                        ],
                        max_length=20,
                        verbose_name="type d'opération",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Refusé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="motif du refus")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de validation"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="valideur",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="transactions.transaction",
                        verbose_name="transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approbation",
                "verbose_name_plural": "Approbations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="transactionapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("transaction", "operation_type"),
                name="unique_pending_approval_per_op",
            ),
        ),
    ]
