# Generated by Django 4.2.29 on 2026-03-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0004_alter_transactionevent_event_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("buyer", "Acheteur"), ("seller", "Vendeur")],
                        max_length=10,
                    ),
                ),
                (
                    "signature_data",
                    models.TextField(help_text="Donnée base64 du canvas de signature"),
                ),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_info", models.TextField(blank=True, default="")),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature de contrat",
                "verbose_name_plural": "Signatures de contrats",
            },
        ),
        migrations.AddConstraint(
            model_name="contractsignature",
            constraint=models.UniqueConstraint(
                fields=("transaction", "role"), name="unique_signature_per_role"
            ),
        ),
    ]
