# Generated by Django 4.2.29 on 2026-03-16 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0005_contractsignature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondevisite",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitor_bons_visite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="visiteur",
            ),
        ),
    ]
