# Generated by Django 5.1.15 on 2026-03-25 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0003_alter_parcelle_status"),
        ("transactions", "0006_alter_bondevisite_visitor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "cotation_type",
                    models.CharField(
                        choices=[
                            ("achat", "Cotation d'achat — 10 % du bien"),
                            ("boutique", "Cotation boutique — Vendeur / Promoteur"),
                        ],
                        default="achat",
                        max_length=20,
                        verbose_name="type de cotation",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="montant cotation (FCFA)",
                    ),
                ),
                (
                    "property_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Prix du bien au moment de la cotation (pour traçabilité).",
                        max_digits=15,
                        null=True,
                        verbose_name="prix du bien (FCFA)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de paiement"),
                            ("paid", "Payée — En attente de validation"),
                            ("validated", "Validée — Droits actifs"),
                            ("expired", "Expirée"),
                            ("refunded", "Remboursée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="référence paiement CinetPay",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("wave", "Wave"),
                            ("carte", "Carte bancaire"),
                            ("virement", "Virement bancaire"),
                        ],
                        max_length=30,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de paiement"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de validation"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'expiration"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parcelle concernée (uniquement pour cotation d'achat).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotations",
                        to="parcelles.parcelle",
                        verbose_name="parcelle",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="payeur",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        help_text="Transaction d'achat définitif où la cotation est déduite.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotation",
                        to="transactions.transaction",
                        verbose_name="transaction liée",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_cotations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotation",
                "verbose_name_plural": "Cotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Boutique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nom de la boutique"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="boutiques/logos/%Y/%m/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        upload_to="boutiques/banners/%Y/%m/",
                        verbose_name="bannière",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email de contact"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de cotation"),
                            ("active", "Active"),
                            ("suspended", "Suspendue"),
                            ("closed", "Fermée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "total_parcelles",
                    models.PositiveIntegerField(
                        default=0, verbose_name="parcelles publiées"
                    ),
                ),
                (
                    "total_ventes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ventes réalisées"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        verbose_name="note moyenne",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boutique",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
                (
                    "cotation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boutique",
                        to="transactions.cotation",
                        verbose_name="cotation de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boutique",
                "verbose_name_plural": "Boutiques",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Créée — En attente d'assignation"),
                            ("assigned", "Assignée à un vérificateur"),
                            ("seller_contacted", "Vendeur contacté"),
                            ("docs_received", "Documents reçus aux locaux"),
                            ("docs_verified", "Documents vérifiés et analysés"),
                            ("docs_watermarked", "Documents filigranés et publiés"),
                            ("client_contacted", "Client contacté pour RDV"),
                            ("rdv_scheduled", "RDV programmé aux locaux"),
                            ("completed", "Finalisée — Achat en cours"),
                            ("cancelled", "Annulée"),
                        ],
                        default="created",
                        max_length=25,
                        verbose_name="statut",
                    ),
                ),
                (
                    "seller_contacted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date contact vendeur"
                    ),
                ),
                (
                    "docs_received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date réception documents"
                    ),
                ),
                (
                    "docs_verified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="date vérification documents",
                    ),
                ),
                (
                    "client_contacted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date contact client"
                    ),
                ),
                (
                    "rdv_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date du RDV aux locaux"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de finalisation"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="notes de vérification"),
                ),
                (
                    "seller_contact_notes",
                    models.TextField(blank=True, verbose_name="notes contact vendeur"),
                ),
                (
                    "client_contact_notes",
                    models.TextField(blank=True, verbose_name="notes contact client"),
                ),
                (
                    "docs_are_authentic",
                    models.BooleanField(
                        help_text="Résultat de la vérification d'authenticité.",
                        null=True,
                        verbose_name="documents authentiques",
                    ),
                ),
                (
                    "analysis_report",
                    models.TextField(blank=True, verbose_name="rapport d'analyse"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_requests_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acheteur",
                    ),
                ),
                (
                    "cotation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="transactions.cotation",
                        verbose_name="cotation source",
                    ),
                ),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_requests",
                        to="parcelles.parcelle",
                        verbose_name="parcelle",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_requests_as_seller",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendeur",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vérificateur assigné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de vérification",
                "verbose_name_plural": "Demandes de vérification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cotation",
            index=models.Index(
                fields=["payer", "-created_at"], name="transaction_payer_i_3bcab1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotation",
            index=models.Index(
                fields=["parcelle", "status"], name="transaction_parcell_04d95e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotation",
            index=models.Index(fields=["status"], name="transaction_status_6f995a_idx"),
        ),
        migrations.AddConstraint(
            model_name="cotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["paid", "validated"])),
                fields=("payer", "parcelle"),
                name="unique_active_cotation_per_buyer_parcelle",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(fields=["status"], name="transaction_status_74f873_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["verifier", "status"], name="transaction_verifie_3b4d28_idx"
            ),
        ),
    ]
