# Generated by Django 5.1.15 on 2026-03-27 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0004_parcelleanalysis"),
        ("transactions", "0007_cotation_boutique_verificationrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Format: FAC-YYYYMM-XXXX",
                        max_length=30,
                        unique=True,
                        verbose_name="numéro de facture",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="référence interne"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=200, verbose_name="nom client (snapshot)"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="email client (snapshot)",
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone client"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("cotation", "Cotation achat"),
                            ("boutique", "Abonnement boutique"),
                            ("promotion", "Campagne promotion"),
                            ("certification", "Certification"),
                            ("visite", "Bon de visite"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("issued", "Émise"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="montant HT (FCFA)",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 pour exonéré.",
                        max_digits=5,
                        verbose_name="taux TVA (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="montant TVA (FCFA)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        verbose_name="montant TTC (FCFA)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
                (
                    "line_items",
                    models.JSONField(
                        default=list,
                        help_text="Liste [{description, quantity, unit_price, total}].",
                        verbose_name="lignes de facture",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="ID transaction CinetPay.",
                        max_length=100,
                        verbose_name="référence paiement",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("wave", "Wave"),
                            ("carte", "Carte bancaire"),
                            ("virement", "Virement"),
                        ],
                        max_length=30,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de paiement"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="invoices/%Y/%m/",
                        verbose_name="fichier PDF",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'émission"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date d'échéance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, verbose_name="notes internes")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "cotation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="transactions.cotation",
                        verbose_name="cotation liée",
                    ),
                ),
                (
                    "parcelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="parcelles.parcelle",
                        verbose_name="parcelle liée",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="transactions.transaction",
                        verbose_name="transaction liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="transaction_invoice_8caeda_idx"
                    ),
                    models.Index(
                        fields=["status"], name="transaction_status_66f61f_idx"
                    ),
                    models.Index(
                        fields=["client"], name="transaction_client__6a61e6_idx"
                    ),
                ],
            },
        ),
    ]
