# Generated by Django 5.1.15 on 2026-03-29 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("boutique", "Boutique"),
                            ("vendeur", "Vendeur"),
                            ("prestation", "Prestation / Transaction"),
                        ],
                        max_length=20,
                        verbose_name="type de cible",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Tres mauvais, 5 = Excellent",
                        verbose_name="note (1-5)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="commentaire"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="L'auteur a effectivement realise une transaction.",
                        verbose_name="avis verifie",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="visible publiquement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="transactions.boutique",
                        verbose_name="boutique",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur cible",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="transactions.transaction",
                        verbose_name="transaction liee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                        name="review_score_1_to_5",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("boutique__isnull", False)),
                        fields=("author", "boutique"),
                        name="unique_review_per_boutique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_user__isnull", False)),
                        fields=("author", "target_user"),
                        name="unique_review_per_vendeur",
                    ),
                ],
            },
        ),
    ]
