# Generated by Django 5.1.15 on 2026-03-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="boutique",
            name="commune",
            field=models.CharField(blank=True, max_length=100, verbose_name="commune"),
        ),
        migrations.AddField(
            model_name="boutique",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="page Facebook"),
        ),
        migrations.AddField(
            model_name="boutique",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="boutique",
            name="specialty",
            field=models.CharField(
                blank=True,
                help_text="Ex: Terrains résidentiels à Cocody, Lotissements à Yamoussoukro",
                max_length=200,
                verbose_name="spécialité",
            ),
        ),
        migrations.AddField(
            model_name="boutique",
            name="theme_color",
            field=models.CharField(
                blank=True,
                default="#0B3D2E",
                help_text="Couleur hexadécimale pour personnaliser votre boutique (ex: #0B3D2E)",
                max_length=7,
                verbose_name="couleur du thème",
            ),
        ),
        migrations.AddField(
            model_name="boutique",
            name="website",
            field=models.URLField(blank=True, verbose_name="site web"),
        ),
        migrations.AddField(
            model_name="boutique",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Numéro WhatsApp pour le bouton de contact (ex: 2250709000000)",
                max_length=20,
                verbose_name="numéro WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="boutique",
            name="whatsapp_message",
            field=models.CharField(
                blank=True,
                default="Bonjour, je suis interesse par vos parcelles sur Eye-Foncier.",
                max_length=300,
                verbose_name="message WhatsApp pré-rempli",
            ),
        ),
    ]
