# Generated by Django 5.1.15 on 2026-02-09 00:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parcelles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelleDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("titre_foncier", "Titre Foncier"),
                            ("acd", "Arrêté de Concession Définitive (ACD)"),
                            ("certificat", "Certificat de propriété"),
                            ("plan", "Plan cadastral"),
                            ("permis", "Permis de construire"),
                            ("attestation", "Attestation villageoise"),
                            ("autre", "Autre document"),
                        ],
                        max_length=30,
                        verbose_name="type de document",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="titre du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/secure/%Y/%m/", verbose_name="fichier"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="Empreinte du fichier pour vérification d'intégrité.",
                        max_length=64,
                        verbose_name="hash SHA-256",
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public — Visible par tous"),
                            ("buyer_only", "Acheteurs vérifiés uniquement"),
                            ("private", "Privé — Admin seulement"),
                        ],
                        default="buyer_only",
                        max_length=20,
                        verbose_name="niveau de confidentialité",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Le document a été vérifié par un administrateur.",
                        verbose_name="vérifié",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="parcelles.parcelle",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de parcelle",
                "verbose_name_plural": "Documents de parcelles",
                "ordering": ["doc_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("action", models.CharField(default="view", max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.parcelledocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log consultation document",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["document", "-timestamp"],
                        name="documents_d_documen_4ef1cc_idx",
                    )
                ],
            },
        ),
    ]
