# Generated by Django 5.1.15 on 2026-02-18 18:02

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parcelles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GISReferenceLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nom de la couche"),
                ),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("flood_zone", "Zones inondables"),
                            ("erosion_zone", "Zones d'érosion"),
                            ("power_line", "Lignes haute tension"),
                            ("pipeline", "Pipelines / Conduites"),
                            ("urban_zone", "Zonage urbanisme"),
                            ("green_zone", "Zones vertes protégées"),
                            ("road_network", "Réseau routier"),
                            ("water_network", "Réseau hydrique"),
                            ("poi", "Points d'intérêt (écoles, hôpitaux)"),
                        ],
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        blank=True, null=True, srid=4326, verbose_name="géométries"
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        upload_to="gis_layers/%Y/%m/",
                        verbose_name="fichier source",
                    ),
                ),
                (
                    "buffer_distance_m",
                    models.FloatField(
                        blank=True,
                        help_text="Zone tampon à appliquer autour de la géométrie.",
                        null=True,
                        verbose_name="distance buffer (m)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Couche SIG de référence",
                "verbose_name_plural": "Couches SIG de référence",
                "ordering": ["layer_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours de génération"),
                            ("ready", "Prêt"),
                            ("error", "Erreur"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="reports/analysis/%Y/%m/",
                        verbose_name="rapport PDF",
                    ),
                ),
                (
                    "qr_verification_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="code QR vérification"
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Copie des scores/risques au moment de la génération.",
                        verbose_name="données du rapport",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de génération"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_reports",
                        to="parcelles.parcelle",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport d'analyse",
                "verbose_name_plural": "Rapports d'analyse",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="budget minimum (FCFA)",
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="budget maximum (FCFA)",
                    ),
                ),
                (
                    "surface_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="surface min (m²)",
                    ),
                ),
                (
                    "surface_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="surface max (m²)",
                    ),
                ),
                (
                    "preferred_land_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex: ["residentiel", "mixte"]',
                        verbose_name="types de terrain préférés",
                    ),
                ),
                (
                    "search_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Polygone de la zone de recherche dessinée sur la carte.",
                        null=True,
                        srid=4326,
                        verbose_name="zone de recherche",
                    ),
                ),
                (
                    "reference_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="point de référence (travail/domicile)",
                    ),
                ),
                (
                    "max_travel_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Temps max accepté entre le terrain et le point de référence.",
                        null=True,
                        verbose_name="temps de trajet max (min)",
                    ),
                ),
                (
                    "lifestyle",
                    models.CharField(
                        choices=[
                            ("urban", "Urbain — Centre-ville"),
                            ("suburban", "Péri-urbain — Banlieue"),
                            ("rural", "Rural — Campagne"),
                            ("mixed", "Sans préférence"),
                        ],
                        default="mixed",
                        max_length=20,
                        verbose_name="style de vie",
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservateur — Sécurité maximale"),
                            ("moderate", "Modéré — Rapport qualité/prix"),
                            ("adventurous", "Aventurier — Opportunités"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="tolérance au risque",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("residence", "Résidence principale"),
                            ("investment", "Investissement locatif"),
                            ("commercial", "Projet commercial"),
                            ("agricultural", "Projet agricole"),
                            ("speculative", "Achat spéculatif (revente)"),
                        ],
                        default="residence",
                        max_length=20,
                        verbose_name="type de projet",
                    ),
                ),
                (
                    "weight_price",
                    models.FloatField(
                        default=0.3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="poids prix (Wp)",
                    ),
                ),
                (
                    "weight_location",
                    models.FloatField(
                        default=0.25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="poids localisation (Wl)",
                    ),
                ),
                (
                    "weight_technical",
                    models.FloatField(
                        default=0.25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="poids technique (Wt)",
                    ),
                ),
                (
                    "weight_seller",
                    models.FloatField(
                        default=0.2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="poids fiabilité vendeur (Wv)",
                    ),
                ),
                (
                    "notify_on_match",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir une alerte si un terrain > 85% de compatibilité.",
                        verbose_name="alertes opportunités",
                    ),
                ),
                (
                    "match_threshold",
                    models.PositiveIntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="seuil d'alerte (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="profil actif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interested_buyers",
                        to="parcelles.zone",
                        verbose_name="zones préférées",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil acheteur",
                "verbose_name_plural": "Profils acheteurs",
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score_price",
                    models.FloatField(default=0, verbose_name="score prix (0-100)"),
                ),
                (
                    "score_location",
                    models.FloatField(
                        default=0, verbose_name="score localisation (0-100)"
                    ),
                ),
                (
                    "score_technical",
                    models.FloatField(
                        default=0, verbose_name="score technique (0-100)"
                    ),
                ),
                (
                    "score_seller",
                    models.FloatField(default=0, verbose_name="score vendeur (0-100)"),
                ),
                (
                    "final_score",
                    models.FloatField(
                        default=0,
                        help_text="Score pondéré : S = Wp·Sp + Wl·Sl + Wt·St + Wv·Sv",
                        verbose_name="score final (0-100)",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="détail du calcul"
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(
                        default=False, verbose_name="notification envoyée"
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="analysis.buyerprofile",
                    ),
                ),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="parcelles.parcelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score de compatibilité",
                "verbose_name_plural": "Scores de compatibilité",
                "ordering": ["-final_score"],
            },
        ),
        migrations.CreateModel(
            name="MatchNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Notification Push"),
                            ("sms", "SMS"),
                            ("inapp", "In-App"),
                        ],
                        default="inapp",
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                ("is_read", models.BooleanField(default=False, verbose_name="lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="lu à"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="analysis.matchscore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification matching",
                "verbose_name_plural": "Notifications matching",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ProximityAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "poi_type",
                    models.CharField(
                        choices=[
                            ("road", "Route bitumée"),
                            ("electricity", "Réseau électrique"),
                            ("water", "Réseau d'eau"),
                            ("school", "École"),
                            ("hospital", "Hôpital / Centre de santé"),
                            ("market", "Marché"),
                            ("transport", "Transport public"),
                            ("police", "Commissariat / Gendarmerie"),
                        ],
                        max_length=20,
                        verbose_name="type d'infrastructure",
                    ),
                ),
                (
                    "distance_m",
                    models.FloatField(
                        blank=True,
                        help_text="Distance à vol d'oiseau vers l'infrastructure la plus proche.",
                        null=True,
                        verbose_name="distance (mètres)",
                    ),
                ),
                (
                    "poi_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="nom du point"
                    ),
                ),
                (
                    "poi_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="localisation POI",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="100 = très proche, 0 = très éloigné.",
                        null=True,
                        verbose_name="score accessibilité (0-100)",
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_analyses",
                        to="parcelles.parcelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse de proximité",
                "verbose_name_plural": "Analyses de proximité",
                "ordering": ["poi_type"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flood_risk",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="low",
                        max_length=15,
                        verbose_name="risque inondation",
                    ),
                ),
                (
                    "erosion_risk",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="low",
                        max_length=15,
                        verbose_name="risque érosion",
                    ),
                ),
                (
                    "slope_risk",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="low",
                        max_length=15,
                        verbose_name="risque pente",
                    ),
                ),
                (
                    "legal_risk",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="low",
                        max_length=15,
                        verbose_name="risque juridique / servitudes",
                    ),
                ),
                (
                    "score_accessibility",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="accessibilité (0-5)",
                    ),
                ),
                (
                    "score_topography",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="topographie (0-5)",
                    ),
                ),
                (
                    "score_legal",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="juridique (0-5)",
                    ),
                ),
                (
                    "score_environment",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="environnement (0-5)",
                    ),
                ),
                (
                    "score_price",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="prix (0-5)",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="score global (0-100)"
                    ),
                ),
                (
                    "overall_risk",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="low",
                        max_length=15,
                        verbose_name="niveau de risque global",
                    ),
                ),
                (
                    "ai_conclusion",
                    models.TextField(
                        blank=True,
                        help_text="Diagnostic automatique. Ex: 'Terrain idéal pour construction résidentielle'.",
                        verbose_name="conclusion IA",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ideal", "Idéal — Construction immédiate"),
                            ("good", "Bon — Travaux mineurs"),
                            ("caution", "Prudence — Études complémentaires"),
                            ("risky", "Risqué — Terrassement important"),
                            ("no_go", "Déconseillé"),
                        ],
                        max_length=50,
                        verbose_name="recommandation",
                    ),
                ),
                ("assessed_at", models.DateTimeField(auto_now=True)),
                (
                    "parcelle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="parcelles.parcelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation des risques",
                "verbose_name_plural": "Évaluations des risques",
            },
        ),
        migrations.CreateModel(
            name="SpatialConstraint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("flood_zone", "Zone inondable"),
                            ("erosion", "Zone d'érosion"),
                            ("power_line", "Servitude — Ligne haute tension"),
                            ("pipeline", "Servitude — Pipeline/Conduite"),
                            ("green_zone", "Zone verte / non constructible"),
                            ("heritage", "Zone patrimoine protégé"),
                            ("road_setback", "Recul routier"),
                            ("custom", "Autre contrainte"),
                        ],
                        max_length=30,
                        verbose_name="type de contrainte",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Attention"),
                            ("critical", "Critique — Bloquant"),
                        ],
                        max_length=15,
                        verbose_name="gravité",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "affected_area_pct",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% surface affectée",
                    ),
                ),
                (
                    "source_layer",
                    models.CharField(
                        blank=True,
                        help_text="Nom du fichier ou couche SIG utilisée.",
                        max_length=200,
                        verbose_name="couche source",
                    ),
                ),
                (
                    "intersection_geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="géométrie intersection",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spatial_constraints",
                        to="parcelles.parcelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrainte spatiale",
                "verbose_name_plural": "Contraintes spatiales",
                "ordering": ["-severity", "constraint_type"],
            },
        ),
        migrations.CreateModel(
            name="TerrainAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "elevation_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="altitude min (m)"
                    ),
                ),
                (
                    "elevation_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="altitude max (m)"
                    ),
                ),
                (
                    "elevation_mean",
                    models.FloatField(
                        blank=True, null=True, verbose_name="altitude moyenne (m)"
                    ),
                ),
                (
                    "elevation_range",
                    models.FloatField(
                        blank=True, null=True, verbose_name="dénivelé (m)"
                    ),
                ),
                (
                    "slope_mean",
                    models.FloatField(
                        blank=True,
                        help_text="Inclinaison moyenne du terrain en pourcentage.",
                        null=True,
                        verbose_name="pente moyenne (%)",
                    ),
                ),
                (
                    "slope_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="pente max (%)"
                    ),
                ),
                (
                    "slope_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "Plat (< 5%)"),
                            ("gentle", "Légère pente (5–10%)"),
                            ("moderate", "Pente modérée (10–15%)"),
                            ("steep", "Forte pente (15–25%)"),
                            ("very_steep", "Très forte pente (> 25%)"),
                        ],
                        max_length=20,
                        verbose_name="catégorie de pente",
                    ),
                ),
                (
                    "slope_is_constructible",
                    models.BooleanField(
                        default=True,
                        help_text="Faux si pente > 15% — coûts de construction élevés.",
                        verbose_name="constructible (pente)",
                    ),
                ),
                (
                    "aspect_dominant",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "Nord"),
                            ("NE", "Nord-Est"),
                            ("E", "Est"),
                            ("SE", "Sud-Est"),
                            ("S", "Sud"),
                            ("SW", "Sud-Ouest"),
                            ("W", "Ouest"),
                            ("NW", "Nord-Ouest"),
                            ("FLAT", "Plat"),
                        ],
                        max_length=5,
                        verbose_name="exposition dominante",
                    ),
                ),
                (
                    "solar_potential",
                    models.FloatField(
                        blank=True,
                        help_text="Score basé sur l'exposition Sud = meilleur.",
                        null=True,
                        verbose_name="potentiel solaire (0-100)",
                    ),
                ),
                (
                    "water_accumulation_risk",
                    models.FloatField(
                        blank=True,
                        help_text="Score de probabilité de stagnation d'eau en cas de pluie.",
                        null=True,
                        verbose_name="risque accumulation eau (0-100)",
                    ),
                ),
                (
                    "drainage_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("bon", "Bon"),
                            ("moyen", "Moyen"),
                            ("mauvais", "Mauvais"),
                        ],
                        max_length=20,
                        verbose_name="qualité du drainage",
                    ),
                ),
                (
                    "technical_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score composite : pente + exposition + drainage + constructibilité.",
                        null=True,
                        verbose_name="score technique (0-100)",
                    ),
                ),
                (
                    "dem_source",
                    models.CharField(
                        blank=True,
                        help_text="Ex: SRTM 30m, Lidar IGN, etc.",
                        max_length=100,
                        verbose_name="source MNT",
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(auto_now=True, verbose_name="date d'analyse"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Histogramme des pentes, stats détaillées, etc.",
                        verbose_name="données brutes",
                    ),
                ),
                (
                    "parcelle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terrain_analysis",
                        to="parcelles.parcelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse de terrain",
                "verbose_name_plural": "Analyses de terrain",
            },
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["-final_score"], name="analysis_ma_final_s_a17f61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["buyer_profile", "-final_score"],
                name="analysis_ma_buyer_p_914593_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchscore",
            unique_together={("buyer_profile", "parcelle")},
        ),
        migrations.AlterUniqueTogether(
            name="proximityanalysis",
            unique_together={("parcelle", "poi_type")},
        ),
    ]
