# Generated by Django 5.1.15 on 2026-02-09 00:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ilot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nom de l'îlot"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="code îlot"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="géométrie"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Îlot",
                "verbose_name_plural": "Îlots",
                "ordering": ["zone", "name"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nom de la zone"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="code zone"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="géométrie"
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="population estimée"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Parcelle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="numéro de lot"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("residentiel", "Résidentiel"),
                            ("commercial", "Commercial"),
                            ("industriel", "Industriel"),
                            ("agricole", "Agricole"),
                            ("mixte", "Mixte"),
                        ],
                        default="residentiel",
                        max_length=20,
                        verbose_name="type de terrain",
                    ),
                ),
                (
                    "surface_m2",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="surface (m²)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="prix (FCFA)"
                    ),
                ),
                (
                    "price_per_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="prix au m² (FCFA)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponible", "🟢 Disponible"),
                            ("reserve", "🟠 Réservé"),
                            ("vendu", "🔴 Vendu"),
                        ],
                        default="disponible",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, verbose_name="validé par géomètre"
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="géométrie de la parcelle"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="centroïde"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="adresse"
                    ),
                ),
                (
                    "title_holder_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom exact figurant sur le titre foncier pour vérification.",
                        max_length=200,
                        verbose_name="nom sur le titre foncier",
                    ),
                ),
                (
                    "trust_badge",
                    models.BooleanField(
                        default=False,
                        help_text="Vrai si le nom du titre correspond au nom du compte.",
                        verbose_name="badge de confiance",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre de vues"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcelles",
                        to="parcelles.ilot",
                        verbose_name="îlot",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_parcelles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcelles",
                        to="parcelles.zone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcelle",
                "verbose_name_plural": "Parcelles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParcelleMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("drone", "Vue drone"),
                            ("plan", "Plan"),
                        ],
                        default="image",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="titre"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="parcelles/medias/%Y/%m/", verbose_name="fichier"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="parcelles/thumbnails/%Y/%m/",
                        verbose_name="miniature",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="parcelles.parcelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média parcelle",
                "verbose_name_plural": "Médias parcelles",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ilot",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ilots",
                to="parcelles.zone",
            ),
        ),
        migrations.AddIndex(
            model_name="parcelle",
            index=models.Index(fields=["status"], name="parcelles_p_status_893174_idx"),
        ),
        migrations.AddIndex(
            model_name="parcelle",
            index=models.Index(fields=["zone"], name="parcelles_p_zone_id_a67a29_idx"),
        ),
        migrations.AddIndex(
            model_name="parcelle",
            index=models.Index(fields=["price"], name="parcelles_p_price_8f38f9_idx"),
        ),
        migrations.AddIndex(
            model_name="parcelle",
            index=models.Index(
                fields=["surface_m2"], name="parcelles_p_surface_89e12f_idx"
            ),
        ),
    ]
