# Generated by Django 5.1.15 on 2026-02-19 00:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("basic", "Standard — 5 000 FCFA / semaine"),
                            ("premium", "Premium — 15 000 FCFA / semaine"),
                            ("boost", "Boost — 25 000 FCFA / semaine"),
                        ],
                        default="basic",
                        max_length=15,
                        verbose_name="type de campagne",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_payment", "En attente de paiement"),
                            ("active", "Active"),
                            ("paused", "En pause"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de fin"
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=1, verbose_name="durée (semaines)"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="montant payé (FCFA)",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="référence paiement"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("virement", "Virement bancaire"),
                            ("carte", "Carte bancaire"),
                        ],
                        max_length=30,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "target_land_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="types de terrain ciblés"
                    ),
                ),
                (
                    "target_budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="budget min cible",
                    ),
                ),
                (
                    "target_budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="budget max cible",
                    ),
                ),
                (
                    "highlight_text",
                    models.CharField(
                        blank=True,
                        help_text="Texte mis en avant dans la promotion.",
                        max_length=200,
                        verbose_name="accroche",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="impressions"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="clics"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="parcelles.parcelle",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_zones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Zones où afficher la promotion. Vide = toutes.",
                        related_name="targeted_promotions",
                        to="parcelles.zone",
                        verbose_name="zones ciblées",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne de promotion",
                "verbose_name_plural": "Campagnes de promotion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParcelleReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "J'aime"),
                            ("favorite", "Favori"),
                            ("interested", "Intéressé"),
                            ("dislike", "Pas intéressé"),
                        ],
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="parcelles.parcelle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réaction",
                "verbose_name_plural": "Réactions",
                "ordering": ["-created_at"],
                "unique_together": {("user", "parcelle", "reaction_type")},
            },
        ),
    ]
