# Generated by Django 4.2.29 on 2026-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0002_promotioncampaign_parcellereaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcelle",
            name="status",
            field=models.CharField(
                choices=[
                    ("disponible", "● Disponible"),
                    ("reserve", "◉ Réservé"),
                    ("vendu", "○ Vendu"),
                ],
                default="disponible",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
