# Generated by Django 5.1.15 on 2026-03-27 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0003_alter_parcelle_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelleAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours d'analyse"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "score_geometry",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Cohérence superficie déclarée vs calculée, qualité du polygone.",
                        verbose_name="score géométrie",
                    ),
                ),
                (
                    "score_documents",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Présence et qualité des documents fonciers.",
                        verbose_name="score documentaire",
                    ),
                ),
                (
                    "score_overlap",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="100 = aucun chevauchement, 0 = conflit total.",
                        verbose_name="score chevauchement",
                    ),
                ),
                (
                    "score_terrain",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Note du contrôle physique par le vérificateur.",
                        verbose_name="score vérification terrain",
                    ),
                ),
                (
                    "score_ownership",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Cohérence propriétaire / historique / titre foncier.",
                        verbose_name="score propriété",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Score pondéré 0-100.",
                        verbose_name="score global",
                    ),
                ),
                (
                    "declared_surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="superficie déclarée (m²)",
                    ),
                ),
                (
                    "computed_surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="superficie calculée (m²)",
                    ),
                ),
                (
                    "surface_deviation_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Écart en % entre superficie déclarée et calculée.",
                        max_digits=5,
                        null=True,
                        verbose_name="écart superficie (%)",
                    ),
                ),
                (
                    "has_overlap",
                    models.BooleanField(
                        default=False, verbose_name="chevauchement détecté"
                    ),
                ),
                (
                    "overlap_parcelles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs des parcelles qui se chevauchent avec celle-ci.",
                        verbose_name="parcelles en chevauchement",
                    ),
                ),
                (
                    "overlap_area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="surface chevauchement (m²)",
                    ),
                ),
                (
                    "has_titre_foncier",
                    models.BooleanField(
                        default=False, verbose_name="titre foncier fourni"
                    ),
                ),
                (
                    "has_attestation",
                    models.BooleanField(
                        default=False, verbose_name="attestation fournie"
                    ),
                ),
                (
                    "has_plan_cadastral",
                    models.BooleanField(
                        default=False, verbose_name="plan cadastral fourni"
                    ),
                ),
                (
                    "has_images_terrain",
                    models.BooleanField(
                        default=False, verbose_name="photos terrain fournies"
                    ),
                ),
                (
                    "docs_authentic",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="documents jugés authentiques",
                    ),
                ),
                (
                    "docs_notes",
                    models.TextField(
                        blank=True, verbose_name="notes vérification documentaire"
                    ),
                ),
                (
                    "ownership_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste [{date, owner, action, reference}].",
                        verbose_name="historique de propriété",
                    ),
                ),
                (
                    "ownership_verified",
                    models.BooleanField(
                        default=False, verbose_name="historique vérifié"
                    ),
                ),
                (
                    "terrain_inspected",
                    models.BooleanField(
                        default=False, verbose_name="inspection terrain effectuée"
                    ),
                ),
                (
                    "terrain_inspection_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date inspection"
                    ),
                ),
                (
                    "terrain_notes",
                    models.TextField(
                        blank=True, verbose_name="rapport inspection terrain"
                    ),
                ),
                (
                    "terrain_photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs ou chemins des photos terrain.",
                        verbose_name="photos inspection",
                    ),
                ),
                (
                    "analysis_report",
                    models.TextField(
                        blank=True, verbose_name="rapport d'analyse complet"
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date analyse"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyzed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="analysé par",
                    ),
                ),
                (
                    "parcelle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="parcelles.parcelle",
                        verbose_name="parcelle",
                    ),
                ),
                (
                    "terrain_inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terrain_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inspecteur terrain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse foncière",
                "verbose_name_plural": "Analyses foncières",
                "ordering": ["-created_at"],
            },
        ),
    ]
