# Generated by Django 5.1.15 on 2026-03-28 11:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0004_parcelleanalysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parcelle",
            name="access_road",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bitume", "Route bitumée"),
                    ("laterite", "Piste latéritique"),
                    ("piste", "Piste non aménagée"),
                    ("aucun", "Aucun accès direct"),
                ],
                max_length=20,
                verbose_name="accès routier",
            ),
        ),
        migrations.AddField(
            model_name="parcelle",
            name="cadastre_ref",
            field=models.CharField(
                blank=True,
                help_text="Référence officielle au cadastre.",
                max_length=100,
                verbose_name="référence cadastrale",
            ),
        ),
        migrations.AddField(
            model_name="parcelle",
            name="electricity",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="électricité disponible"
            ),
        ),
        migrations.AddField(
            model_name="parcelle",
            name="ilot_number",
            field=models.CharField(
                blank=True,
                help_text="Numéro d'îlot tel qu'indiqué sur le plan cadastral.",
                max_length=50,
                verbose_name="numéro d'îlot",
            ),
        ),
        migrations.AddField(
            model_name="parcelle",
            name="soil_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("argileux", "Argileux"),
                    ("sableux", "Sableux"),
                    ("lateritique", "Latéritique"),
                    ("rocheux", "Rocheux"),
                    ("mixte", "Mixte"),
                ],
                max_length=30,
                verbose_name="type de sol",
            ),
        ),
        migrations.AddField(
            model_name="parcelle",
            name="topography",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plat", "Plat"),
                    ("legere_pente", "Légère pente"),
                    ("vallonne", "Vallonné"),
                    ("accidente", "Accidenté"),
                ],
                max_length=20,
                verbose_name="topographie",
            ),
        ),
        migrations.AddField(
            model_name="parcelle",
            name="water_access",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="accès à l'eau"
            ),
        ),
        migrations.CreateModel(
            name="Lotissement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="nom du lotissement"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identifiant unique (ex: LOT-ABJ-001).",
                        max_length=50,
                        unique=True,
                        verbose_name="code lotissement",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis pour validation"),
                            ("approved", "Approuvé"),
                            ("active", "Actif — en vente"),
                            ("completed", "Terminé — tout vendu"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Contour global du terrain à morceler.",
                        srid=4326,
                        verbose_name="périmètre du lotissement",
                    ),
                ),
                (
                    "total_surface_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="surface totale (m²)",
                    ),
                ),
                (
                    "plan_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image du plan (JPG, PNG).",
                        upload_to="lotissements/plans/%Y/%m/",
                        verbose_name="plan de morcellement",
                    ),
                ),
                (
                    "plan_shapefile",
                    models.FileField(
                        blank=True,
                        help_text="Fichier Shapefile (.zip) ou GeoJSON du morcellement.",
                        upload_to="lotissements/sig/%Y/%m/",
                        verbose_name="plan SIG",
                    ),
                ),
                (
                    "total_ilots",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre d'îlots"
                    ),
                ),
                (
                    "total_lots",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre de lots"
                    ),
                ),
                (
                    "lots_sold",
                    models.PositiveIntegerField(default=0, verbose_name="lots vendus"),
                ),
                (
                    "price_per_m2_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="prix min/m² (FCFA)",
                    ),
                ),
                (
                    "price_per_m2_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="prix max/m² (FCFA)",
                    ),
                ),
                (
                    "has_water",
                    models.BooleanField(default=False, verbose_name="eau potable"),
                ),
                (
                    "has_electricity",
                    models.BooleanField(default=False, verbose_name="électricité"),
                ),
                (
                    "has_road",
                    models.BooleanField(default=False, verbose_name="voirie bitumée"),
                ),
                (
                    "has_drainage",
                    models.BooleanField(default=False, verbose_name="assainissement"),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date d'approbation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promoteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotissements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="promoteur",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lotissements",
                        to="parcelles.zone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lotissement",
                "verbose_name_plural": "Lotissements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="parcelle",
            name="lotissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcelles",
                to="parcelles.lotissement",
                verbose_name="lotissement",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcelle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ilot__isnull", False)),
                fields=("lot_number", "ilot"),
                name="unique_lot_per_ilot",
            ),
        ),
    ]
