# Generated by Django 5.1.15 on 2026-03-29 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0005_parcelle_access_road_parcelle_cadastre_ref_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lotissement",
            name="approval_reference",
            field=models.CharField(
                blank=True,
                help_text="Référence de l'arrêté d'approbation.",
                max_length=200,
                verbose_name="numéro d'arrêté",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="arrete_approbation",
            field=models.FileField(
                blank=True,
                help_text="Preuve officielle de la légalité du lotissement (ministère de l'Urbanisme).",
                upload_to="lotissements/docs/%Y/%m/",
                verbose_name="arrêté d'approbation",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="attestation_villageoise",
            field=models.FileField(
                blank=True,
                help_text="Document administratif de base.",
                upload_to="lotissements/docs/%Y/%m/",
                verbose_name="attestation villageoise / lettre d'attribution",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="certificat_propriete",
            field=models.FileField(
                blank=True,
                help_text="Indispensable pour vérifier l'absence d'hypothèques ou de litiges.",
                upload_to="lotissements/docs/%Y/%m/",
                verbose_name="certificat de propriété / état foncier",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="dossier_technique",
            field=models.FileField(
                blank=True,
                help_text="Établi par un géomètre expert.",
                upload_to="lotissements/docs/%Y/%m/",
                verbose_name="dossier technique",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="has_public_spaces",
            field=models.BooleanField(default=False, verbose_name="espaces publics"),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Le lotissement a été approuvé par le ministère de l'Urbanisme.",
                verbose_name="approuvé par le ministère",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de validation"
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_lotissements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validé par (géomètre)",
            ),
        ),
        migrations.AddField(
            model_name="lotissement",
            name="validation_notes",
            field=models.TextField(blank=True, verbose_name="notes de validation"),
        ),
        migrations.AlterField(
            model_name="parcelleanalysis",
            name="surface_deviation_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Écart en % entre superficie déclarée et calculée.",
                max_digits=10,
                null=True,
                verbose_name="écart superficie (%)",
            ),
        ),
    ]
