# Generated by Django 5.1.15 on 2026-03-30 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcelles", "0006_lotissement_approval_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="parcelle",
            index=models.Index(fields=["owner"], name="parcelles_p_owner_i_d284aa_idx"),
        ),
        migrations.AddIndex(
            model_name="parcelle",
            index=models.Index(
                fields=["owner", "-created_at"], name="parcelles_p_owner_i_6a295f_idx"
            ),
        ),
    ]
