# Generated by Django 5.1.15 on 2026-02-19 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="bi-folder",
                        help_text="Classe CSS Bootstrap Icons (ex: bi-house, bi-map)",
                        max_length=50,
                        verbose_name="icône Bootstrap",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("important", "Important"),
                            ("urgent", "Urgent"),
                        ],
                        default="info",
                        max_length=15,
                        verbose_name="priorité",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="épinglée"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expire le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("slug", models.SlugField(max_length=350, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="extrait"
                    ),
                ),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/articles/%Y/%m/",
                        verbose_name="image de couverture",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags séparés par des virgules",
                        max_length=500,
                        verbose_name="tags",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="mis en avant"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="vues"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de publication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="content.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Documentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("slug", models.SlugField(max_length=350, unique=True)),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide utilisateur"),
                            ("faq", "FAQ"),
                            ("legal", "Mentions légales"),
                            ("procedure", "Procédure"),
                            ("api", "Documentation API"),
                        ],
                        default="guide",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-book", max_length=50, verbose_name="icône"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="content.documentation",
                        verbose_name="page parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documentation",
                "verbose_name_plural": "Documentation",
                "ordering": ["order", "title"],
            },
        ),
    ]
