# Generated by Django 4.2.29 on 2026-03-15 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notifications email"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False, verbose_name="notifications SMS"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notifications push"
                    ),
                ),
                (
                    "inapp_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notifications in-app"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Ex: 22:00 — pas de SMS/push pendant cette période",
                        null=True,
                        verbose_name="début heures calmes",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="Ex: 07:00",
                        null=True,
                        verbose_name="fin heures calmes",
                    ),
                ),
                (
                    "disabled_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des types de notification à ignorer",
                        verbose_name="types désactivés",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("transaction_status", "Statut transaction"),
                            ("payment_confirmed", "Paiement confirmé"),
                            ("payment_reminder", "Rappel de paiement"),
                            ("match_found", "Correspondance trouvée"),
                            ("visit_request", "Demande de visite"),
                            ("visit_confirmed", "Visite confirmée"),
                            ("kyc_update", "Mise à jour KYC"),
                            ("document_ready", "Document disponible"),
                            ("escrow_update", "Mise à jour séquestre"),
                            ("scoring_update", "Mise à jour scoring"),
                            ("system", "Système"),
                        ],
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("inapp", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                        ],
                        default="inapp",
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="données"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="lu le"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="envoyé")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyé le"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="erreur d'envoi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["is_read", "recipient"],
                        name="notificatio_is_read_87447e_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_d8746a_idx",
                    ),
                ],
            },
        ),
    ]
