# Generated by Django 4.2.29 on 2026-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Token Firebase Cloud Messaging du device",
                max_length=500,
                verbose_name="token FCM",
            ),
        ),
    ]
