# Generated by Django 5.1.15 on 2026-03-30 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference_fcm_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En file d'attente"),
                            ("sending", "En cours d'envoi"),
                            ("sent", "Envoyé"),
                            ("delivered", "Délivré"),
                            ("failed", "Échoué"),
                            ("retrying", "Nouvelle tentative"),
                        ],
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("inapp", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push"),
                        ],
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Ex: twilio, infobip, fcm, smtp",
                        max_length=50,
                        verbose_name="fournisseur",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="ID message fournisseur",
                    ),
                ),
                (
                    "error_detail",
                    models.TextField(blank=True, verbose_name="détail erreur"),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="réponse fournisseur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de notification",
                "verbose_name_plural": "Logs de notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Basse"),
                    ("normal", "Normale"),
                    ("high", "Haute"),
                    ("urgent", "Urgente"),
                ],
                default="normal",
                max_length=10,
                verbose_name="priorité",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="retry_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="tentatives"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="whatsapp_consent",
            field=models.BooleanField(
                default=False,
                help_text="L'utilisateur a donné son consentement pour recevoir des messages WhatsApp",
                verbose_name="consentement WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="whatsapp_enabled",
            field=models.BooleanField(
                default=False, verbose_name="notifications WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numéro au format international (ex: +225XXXXXXXXXX)",
                max_length=20,
                verbose_name="numéro WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="whatsapp_verified",
            field=models.BooleanField(
                default=False,
                help_text="Le numéro WhatsApp a été vérifié",
                verbose_name="WhatsApp vérifié",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("inapp", "In-App"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Push"),
                ],
                default="inapp",
                max_length=10,
                verbose_name="canal",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("transaction_status", "Statut transaction"),
                    ("payment_confirmed", "Paiement confirmé"),
                    ("payment_reminder", "Rappel de paiement"),
                    ("escrow_update", "Mise à jour séquestre"),
                    ("scoring_update", "Mise à jour scoring"),
                    ("parcelle_published", "Parcelle publiée"),
                    ("parcelle_validated", "Parcelle validée"),
                    ("parcelle_rejected", "Parcelle rejetée"),
                    ("parcelle_interest", "Intérêt pour une parcelle"),
                    ("match_found", "Correspondance trouvée"),
                    ("visit_request", "Demande de visite"),
                    ("visit_confirmed", "Visite confirmée"),
                    ("new_message", "Nouveau message"),
                    ("new_review", "Nouvel avis"),
                    ("client_request", "Demande client"),
                    ("kyc_update", "Mise à jour KYC"),
                    ("document_ready", "Document disponible"),
                    ("account_update", "Mise à jour compte"),
                    ("welcome", "Bienvenue"),
                    ("system", "Système"),
                ],
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="quiet_hours_start",
            field=models.TimeField(
                blank=True,
                help_text="Ex: 22:00 — pas de SMS/push/WhatsApp pendant cette période",
                null=True,
                verbose_name="début heures calmes",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["channel", "is_sent"], name="notificatio_channel_747fd1_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="notifications.notification",
                verbose_name="notification",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["notification", "-created_at"],
                name="notificatio_notific_d8c030_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status", "channel"], name="notificatio_status_d69daf_idx"
            ),
        ),
    ]
