# Generated by Django 5.1.15 on 2026-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationlog_notification_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("transaction_status", "Statut transaction"),
                    ("payment_confirmed", "Paiement confirmé"),
                    ("payment_reminder", "Rappel de paiement"),
                    ("escrow_update", "Mise à jour séquestre"),
                    ("scoring_update", "Mise à jour scoring"),
                    ("new_order", "Nouvelle commande"),
                    ("parcelle_published", "Parcelle publiée"),
                    ("parcelle_validated", "Parcelle validée"),
                    ("parcelle_rejected", "Parcelle rejetée"),
                    ("parcelle_interest", "Intérêt pour une parcelle"),
                    ("match_found", "Correspondance trouvée"),
                    ("visit_request", "Demande de visite"),
                    ("visit_confirmed", "Visite confirmée"),
                    ("new_message", "Nouveau message"),
                    ("new_review", "Nouvel avis"),
                    ("client_request", "Demande client"),
                    ("kyc_update", "Mise à jour KYC"),
                    ("document_ready", "Document disponible"),
                    ("account_update", "Mise à jour compte"),
                    ("welcome", "Bienvenue"),
                    ("boutique_activated", "Boutique activée"),
                    ("boutique_update", "Mise à jour boutique"),
                    ("system", "Système"),
                ],
                max_length=30,
                verbose_name="type",
            ),
        ),
    ]
